services:
  cbkt-api-cadastro:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cbkt-api-cadastro
    image: cbkt-api-cadastro
    restart: unless-stopped

    ports:
      - 8081:8081

    networks:
      - web

    labels:
      - "traefik.enable=true"

      - "traefik.docker.network=web"
      # Regra simplificada (PathPrefix já cobre com e sem barra final)
      - "traefik.http.routers.cbkt-cadastro.rule=Host(`cbkt.mmc.dev.br`) && PathPrefix(`/api/cadastro`)"
      - "traefik.http.routers.cbkt-cadastro.entrypoints=websecure"
      - "traefik.http.routers.cbkt-cadastro.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cbkt-cadastro.priority=60"
      
      # Strip Prefix
      - "traefik.http.middlewares.cbkt-cadastro-stripprefix.stripprefix.prefixes=/api/cadastro"
      - "traefik.http.routers.cbkt-cadastro.middlewares=cbkt-cadastro-stripprefix@docker"

      # Porta Interna (Garantindo que bata na 8081)
      - "traefik.http.services.cbkt-cadastro.loadbalancer.server.port=8081"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web:
    external: true
