spring.profiles.default=dev

# Nome da aplicação
spring.application.name=cbkt-api-cadastro

# Porta do servidor
server.port=8081

# Logging
logging.level.org.springframework=INFO

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Acessando propriedades padrão do Maven
info.app.name=${project.name}
info.app.version=${project.version}
info.app.groupId=${project.groupId}

# Exemplo de uso em uma mensagem de log formatada
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%project.version] %msg%n