-- ============================================================================
-- CRIA TABELA CLUBE_INSTRUTOR
-- Mantém lista de atletas que são instrutores de um clube
-- ============================================================================
CREATE TABLE IF NOT EXISTS CLUBE_INSTRUTOR (
    ID BIGSERIAL PRIMARY KEY,
    CODIGOCLUBE BIGINT NOT NULL REFERENCES CLUBE (CODIGOCLUBE),
    CODIGOATLETA BIGINT NOT NULL REFERENCES ATLETA (CODIGOATLETA),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ATIVO BOOLEAN DEFAULT TRUE,
    OBSERVACAO VARCHAR(500),
    CRIADO_EM TIMESTAMP DEFAULT NOW(),
    ATUALIZADO_EM TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_clube_instrutor_ativo ON CLUBE_INSTRUTOR (CODIGOCLUBE, CODIGOATLETA, ATIVO);
CREATE INDEX IF NOT EXISTS idx_clube_instrutor_clube ON CLUBE_INSTRUTOR (CODIGOCLUBE);
CREATE INDEX IF NOT EXISTS idx_clube_instrutor_atleta ON CLUBE_INSTRUTOR (CODIGOATLETA);
